apiVersion: v1
kind: Service
metadata:
  name: covidtracker2
spec:
  selector:
    app: covidtracker2
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidtracker2
  labels:
    app: covidtracker2
spec:
  selector:
    matchLabels:
      app: covidtracker2
  replicas: 1
  template:
    metadata:
      labels:
        app: covidtracker2
    spec:
      containers:
      - name: covidtracker2
        image: de.icr.io/covidtracker_ns2/new_repo2:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"


          