apiVersion: v1
kind: Service
metadata:
  name: covidtracker
spec:
  selector:
    app: covidtracker
  ports:
  - port: 5000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: covidtracker
  labels:
    app: covidtracker
spec:
  selector:
    matchLabels:
      app: covidtracker
  replicas: 1
  template:
    metadata:
      labels:
        app: covidtracker
    spec:
      containers:
      - name: covidtracker
        image: us.icr.io/covidtracker_ns/new_repo:latest
        ports:
        - containerPort: 5000
        env:
        - name: DISABLE_WEB_APP
          value: "false"